/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as _protectedRouteRouteImport } from './routes/__protected/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as _protectedApplicationsRouteImport } from './routes/__protected/applications'
import { Route as _protectedCvsIndexRouteImport } from './routes/__protected/cvs/index'
import { Route as _protectedCvsCvIdRouteImport } from './routes/__protected/cvs/$cvId'

const _protectedRouteRoute = _protectedRouteRouteImport.update({
  id: '/__protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const _protectedApplicationsRoute = _protectedApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => _protectedRouteRoute,
} as any)
const _protectedCvsIndexRoute = _protectedCvsIndexRouteImport.update({
  id: '/cvs/',
  path: '/cvs/',
  getParentRoute: () => _protectedRouteRoute,
} as any)
const _protectedCvsCvIdRoute = _protectedCvsCvIdRouteImport.update({
  id: '/cvs/$cvId',
  path: '/cvs/$cvId',
  getParentRoute: () => _protectedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/applications': typeof _protectedApplicationsRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/cvs/$cvId': typeof _protectedCvsCvIdRoute
  '/cvs/': typeof _protectedCvsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/applications': typeof _protectedApplicationsRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/cvs/$cvId': typeof _protectedCvsCvIdRoute
  '/cvs': typeof _protectedCvsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/__protected': typeof _protectedRouteRouteWithChildren
  '/__protected/applications': typeof _protectedApplicationsRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/__protected/cvs/$cvId': typeof _protectedCvsCvIdRoute
  '/__protected/cvs/': typeof _protectedCvsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/applications' | '/auth/sign-up' | '/cvs/$cvId' | '/cvs/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/applications' | '/auth/sign-up' | '/cvs/$cvId' | '/cvs'
  id:
    | '__root__'
    | '/'
    | '/__protected'
    | '/__protected/applications'
    | '/auth/sign-up'
    | '/__protected/cvs/$cvId'
    | '/__protected/cvs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  _protectedRouteRoute: typeof _protectedRouteRouteWithChildren
  AuthSignUpRoute: typeof AuthSignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/__protected': {
      id: '/__protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof _protectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__protected/applications': {
      id: '/__protected/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof _protectedApplicationsRouteImport
      parentRoute: typeof _protectedRouteRoute
    }
    '/__protected/cvs/': {
      id: '/__protected/cvs/'
      path: '/cvs'
      fullPath: '/cvs/'
      preLoaderRoute: typeof _protectedCvsIndexRouteImport
      parentRoute: typeof _protectedRouteRoute
    }
    '/__protected/cvs/$cvId': {
      id: '/__protected/cvs/$cvId'
      path: '/cvs/$cvId'
      fullPath: '/cvs/$cvId'
      preLoaderRoute: typeof _protectedCvsCvIdRouteImport
      parentRoute: typeof _protectedRouteRoute
    }
  }
}

interface _protectedRouteRouteChildren {
  _protectedApplicationsRoute: typeof _protectedApplicationsRoute
  _protectedCvsCvIdRoute: typeof _protectedCvsCvIdRoute
  _protectedCvsIndexRoute: typeof _protectedCvsIndexRoute
}

const _protectedRouteRouteChildren: _protectedRouteRouteChildren = {
  _protectedApplicationsRoute: _protectedApplicationsRoute,
  _protectedCvsCvIdRoute: _protectedCvsCvIdRoute,
  _protectedCvsIndexRoute: _protectedCvsIndexRoute,
}

const _protectedRouteRouteWithChildren = _protectedRouteRoute._addFileChildren(
  _protectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  _protectedRouteRoute: _protectedRouteRouteWithChildren,
  AuthSignUpRoute: AuthSignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
