/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as _protectedRouteRouteImport } from './routes/__protected/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignOutRouteImport } from './routes/auth/sign-out'
import { Route as _protectedDashboardRouteImport } from './routes/__protected/dashboard'
import { Route as _protectedCvsRouteImport } from './routes/__protected/cvs'
import { Route as _protectedApplicationsRouteImport } from './routes/__protected/applications'

const _protectedRouteRoute = _protectedRouteRouteImport.update({
  id: '/__protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignOutRoute = AuthSignOutRouteImport.update({
  id: '/auth/sign-out',
  path: '/auth/sign-out',
  getParentRoute: () => rootRouteImport,
} as any)
const _protectedDashboardRoute = _protectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => _protectedRouteRoute,
} as any)
const _protectedCvsRoute = _protectedCvsRouteImport.update({
  id: '/cvs',
  path: '/cvs',
  getParentRoute: () => _protectedRouteRoute,
} as any)
const _protectedApplicationsRoute = _protectedApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => _protectedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/applications': typeof _protectedApplicationsRoute
  '/cvs': typeof _protectedCvsRoute
  '/dashboard': typeof _protectedDashboardRoute
  '/auth/sign-out': typeof AuthSignOutRoute
  '/auth/sign-up': typeof AuthSignUpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/applications': typeof _protectedApplicationsRoute
  '/cvs': typeof _protectedCvsRoute
  '/dashboard': typeof _protectedDashboardRoute
  '/auth/sign-out': typeof AuthSignOutRoute
  '/auth/sign-up': typeof AuthSignUpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/__protected': typeof _protectedRouteRouteWithChildren
  '/__protected/applications': typeof _protectedApplicationsRoute
  '/__protected/cvs': typeof _protectedCvsRoute
  '/__protected/dashboard': typeof _protectedDashboardRoute
  '/auth/sign-out': typeof AuthSignOutRoute
  '/auth/sign-up': typeof AuthSignUpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applications'
    | '/cvs'
    | '/dashboard'
    | '/auth/sign-out'
    | '/auth/sign-up'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/applications'
    | '/cvs'
    | '/dashboard'
    | '/auth/sign-out'
    | '/auth/sign-up'
  id:
    | '__root__'
    | '/'
    | '/__protected'
    | '/__protected/applications'
    | '/__protected/cvs'
    | '/__protected/dashboard'
    | '/auth/sign-out'
    | '/auth/sign-up'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  _protectedRouteRoute: typeof _protectedRouteRouteWithChildren
  AuthSignOutRoute: typeof AuthSignOutRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/__protected': {
      id: '/__protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof _protectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-out': {
      id: '/auth/sign-out'
      path: '/auth/sign-out'
      fullPath: '/auth/sign-out'
      preLoaderRoute: typeof AuthSignOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__protected/dashboard': {
      id: '/__protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof _protectedDashboardRouteImport
      parentRoute: typeof _protectedRouteRoute
    }
    '/__protected/cvs': {
      id: '/__protected/cvs'
      path: '/cvs'
      fullPath: '/cvs'
      preLoaderRoute: typeof _protectedCvsRouteImport
      parentRoute: typeof _protectedRouteRoute
    }
    '/__protected/applications': {
      id: '/__protected/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof _protectedApplicationsRouteImport
      parentRoute: typeof _protectedRouteRoute
    }
  }
}

interface _protectedRouteRouteChildren {
  _protectedApplicationsRoute: typeof _protectedApplicationsRoute
  _protectedCvsRoute: typeof _protectedCvsRoute
  _protectedDashboardRoute: typeof _protectedDashboardRoute
}

const _protectedRouteRouteChildren: _protectedRouteRouteChildren = {
  _protectedApplicationsRoute: _protectedApplicationsRoute,
  _protectedCvsRoute: _protectedCvsRoute,
  _protectedDashboardRoute: _protectedDashboardRoute,
}

const _protectedRouteRouteWithChildren = _protectedRouteRoute._addFileChildren(
  _protectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  _protectedRouteRoute: _protectedRouteRouteWithChildren,
  AuthSignOutRoute: AuthSignOutRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
