/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as SignUpRouteImport } from "./routes/sign-up";
import { Route as SignInRouteImport } from "./routes/sign-in";
import { Route as ProtectedRouteImport } from "./routes/_protected";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as ProtectedDashboardRouteImport } from "./routes/_protected/dashboard";
import { Route as ProtectedCvsRouteImport } from "./routes/_protected/cvs";
import { Route as ProtectedApplicationsRouteImport } from "./routes/_protected/applications";
import { Route as ProtectedApplicationsApplicationsIdRouteImport } from "./routes/_protected/application.$applicationsId";

const SignUpRoute = SignUpRouteImport.update({
  id: "/sign-up",
  path: "/sign-up",
  getParentRoute: () => rootRouteImport,
} as any);
const SignInRoute = SignInRouteImport.update({
  id: "/sign-in",
  path: "/sign-in",
  getParentRoute: () => rootRouteImport,
} as any);
const ProtectedRoute = ProtectedRouteImport.update({
  id: "/_protected",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => ProtectedRoute,
} as any);
const ProtectedCvsRoute = ProtectedCvsRouteImport.update({
  id: "/cvs",
  path: "/cvs",
  getParentRoute: () => ProtectedRoute,
} as any);
const ProtectedApplicationsRoute = ProtectedApplicationsRouteImport.update({
  id: "/applications",
  path: "/applications",
  getParentRoute: () => ProtectedRoute,
} as any);
const ProtectedApplicationsApplicationsIdRoute = ProtectedApplicationsApplicationsIdRouteImport.update({
  id: "/$applicationsId",
  path: "/$applicationsId",
  getParentRoute: () => ProtectedApplicationsRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/sign-in": typeof SignInRoute;
  "/sign-up": typeof SignUpRoute;
  "/applications": typeof ProtectedApplicationsRouteWithChildren;
  "/cvs": typeof ProtectedCvsRoute;
  "/dashboard": typeof ProtectedDashboardRoute;
  "/applications/$applicationsId": typeof ProtectedApplicationsApplicationsIdRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/sign-in": typeof SignInRoute;
  "/sign-up": typeof SignUpRoute;
  "/applications": typeof ProtectedApplicationsRouteWithChildren;
  "/cvs": typeof ProtectedCvsRoute;
  "/dashboard": typeof ProtectedDashboardRoute;
  "/applications/$applicationsId": typeof ProtectedApplicationsApplicationsIdRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/_protected": typeof ProtectedRouteWithChildren;
  "/sign-in": typeof SignInRoute;
  "/sign-up": typeof SignUpRoute;
  "/_protected/applications": typeof ProtectedApplicationsRouteWithChildren;
  "/_protected/cvs": typeof ProtectedCvsRoute;
  "/_protected/dashboard": typeof ProtectedDashboardRoute;
  "/_protected/applications/$applicationsId": typeof ProtectedApplicationsApplicationsIdRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/sign-in" | "/sign-up" | "/applications" | "/cvs" | "/dashboard" | "/applications/$applicationsId";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/sign-in" | "/sign-up" | "/applications" | "/cvs" | "/dashboard" | "/applications/$applicationsId";
  id:
    | "__root__"
    | "/"
    | "/_protected"
    | "/sign-in"
    | "/sign-up"
    | "/_protected/applications"
    | "/_protected/cvs"
    | "/_protected/dashboard"
    | "/_protected/applications/$applicationsId";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  ProtectedRoute: typeof ProtectedRouteWithChildren;
  SignInRoute: typeof SignInRoute;
  SignUpRoute: typeof SignUpRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/sign-up": {
      id: "/sign-up";
      path: "/sign-up";
      fullPath: "/sign-up";
      preLoaderRoute: typeof SignUpRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/sign-in": {
      id: "/sign-in";
      path: "/sign-in";
      fullPath: "/sign-in";
      preLoaderRoute: typeof SignInRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_protected": {
      id: "/_protected";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof ProtectedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_protected/dashboard": {
      id: "/_protected/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof ProtectedDashboardRouteImport;
      parentRoute: typeof ProtectedRoute;
    };
    "/_protected/cvs": {
      id: "/_protected/cvs";
      path: "/cvs";
      fullPath: "/cvs";
      preLoaderRoute: typeof ProtectedCvsRouteImport;
      parentRoute: typeof ProtectedRoute;
    };
    "/_protected/applications": {
      id: "/_protected/applications";
      path: "/applications";
      fullPath: "/applications";
      preLoaderRoute: typeof ProtectedApplicationsRouteImport;
      parentRoute: typeof ProtectedRoute;
    };
    "/_protected/applications/$applicationsId": {
      id: "/_protected/applications/$applicationsId";
      path: "/$applicationsId";
      fullPath: "/applications/$applicationsId";
      preLoaderRoute: typeof ProtectedApplicationsApplicationsIdRouteImport;
      parentRoute: typeof ProtectedApplicationsRoute;
    };
  }
}

interface ProtectedApplicationsRouteChildren {
  ProtectedApplicationsApplicationsIdRoute: typeof ProtectedApplicationsApplicationsIdRoute;
}

const ProtectedApplicationsRouteChildren: ProtectedApplicationsRouteChildren = {
  ProtectedApplicationsApplicationsIdRoute: ProtectedApplicationsApplicationsIdRoute,
};

const ProtectedApplicationsRouteWithChildren = ProtectedApplicationsRoute._addFileChildren(ProtectedApplicationsRouteChildren);

interface ProtectedRouteChildren {
  ProtectedApplicationsRoute: typeof ProtectedApplicationsRouteWithChildren;
  ProtectedCvsRoute: typeof ProtectedCvsRoute;
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute;
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedApplicationsRoute: ProtectedApplicationsRouteWithChildren,
  ProtectedCvsRoute: ProtectedCvsRoute,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
};

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(ProtectedRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
};
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>();
