services:
  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    ports:
      - '5005:5005'
    env_file:
      - apps/server/.env.development
    volumes:
      - .:/workspaces/Applera
      - /workspaces/Applera/node_modules
      - /workspaces/Applera/apps/server/node_modules
    command: pnpm dev

  client:
    build:
      context: .
      dockerfile: apps/client/Dockerfile
    ports:
      - '5173:80'
    env_file:
      - apps/client/.env.development
    depends_on:
      - server
    volumes:
      - .:/workspaces/Applera
      - /workspaces/Applera/node_modules
      - /workspaces/Applera/apps/client/node_modules
