import { BulletList, LegalPage } from '../components/ui/legalPage';

export function TermsPage() {
  return (
    <LegalPage
      title="Terms of Service"
      lastUpdated="June 2026"
      intro="By using Applera, you agree to these terms. If you disagree with any part, please do not use the service."
      sections={[
        {
          title: 'What Applera Does',
          content: (
            <p>
              Applera is an AI-powered job application tool. You provide a CV and a job listing, and
              the service generates a tailored cover letter, match score, CV summary, and email
              draft.
            </p>
          ),
        },
        {
          title: 'AI Disclaimer',
          content: (
            <p>
              All output is generated by AI and may be inaccurate, incomplete, or unsuitable for
              your specific situation. You are responsible for reviewing all content before sending
              it to employers. Applera makes no guarantees about the quality or effectiveness of
              generated content.
            </p>
          ),
        },
        {
          title: 'Acceptable Use',
          content: (
            <>
              <p className="mb-3">
                You may use Applera for personal job applications. You may not:
              </p>
              <BulletList
                items={[
                  'Use the service for illegal purposes',
                  "Upload content you don't have rights to",
                  'Attempt to reverse engineer or abuse the service',
                  'Use the service to generate spam or bulk applications',
                  'Impersonate other people in generated content',
                ]}
              />
            </>
          ),
        },
        {
          title: 'Your Data',
          content: (
            <>
              <p>
                You retain ownership of all content you upload. By using Applera, you grant us the
                right to process your CV and job listing data solely to provide the service. We do
                not sell or share your data with third parties. See our{' '}
                <a
                  href="/privacy"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-primary underline underline-offset-2"
                >
                  Privacy Policy
                </a>{' '}
                for full details.
              </p>
            </>
          ),
        },
        {
          title: 'No Warranties',
          content: (
            <p>
              Applera is provided "as is" without warranties of any kind. We do not guarantee
              uptime, accuracy of AI output, or that the service will help you get a job.
            </p>
          ),
        },
        {
          title: 'Limitation of Liability',
          content: (
            <p>
              To the fullest extent permitted by law, Applera and its developers are not liable for
              any damages arising from your use of the service, including data loss, missed job
              opportunities, or reliance on AI-generated content.
            </p>
          ),
        },
        {
          title: 'Account Termination',
          content: (
            <p>
              You may delete your account at any time. We may suspend or terminate accounts that
              violate these terms. We will attempt to notify you before termination except in cases
              of clear abuse.
            </p>
          ),
        },
        {
          title: 'Changes to these Terms',
          content: (
            <p>
              We may update these terms from time to time. Continued use of the service after
              changes constitutes acceptance. Significant changes will be communicated via email
              where possible.
            </p>
          ),
        },
        {
          title: 'Contact',
          content: (
            <p>
              For questions about these terms, reach out via{' '}
              <a
                href="https://github.com/LakBud/Applera"
                target="_blank"
                rel="noopener noreferrer"
                className="text-primary underline underline-offset-2"
              >
                GitHub
              </a>{' '}
              by creating an issue.
            </p>
          ),
        },
      ]}
    />
  );
}
